# azure-pipelines-frontend.yml
# This pipeline builds and deploys the React frontend to Azure Static Web Apps

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  staticWebAppName: 'edusyncfront'  # Replace with your actual SWA name

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build React App'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'              # React app is at the root
    output_location: 'build'       # CRA outputs to 'build' by default
    azure_static_web_apps_api_token: $(deployment_token)
  displayName: 'Deploy to Azure Static Web Apps'
